export const GET_CARDS = "GET_CARDS_ACTION";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY_ACTION";
export const SET_LOADING = "SET_LOADING_ACTION";
export const SET_SORT_CARDS = "SET_SORT_CARDS_ACTION";
