export const ADD_PRODUCT = "ADD_PRODUCT_TO_BASKET_ACTION";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT_IN_BASKET_ACTION";
export const INCREMENT = "SET_INCREMENT_ACTION";
export const DECREMENT = "SET_DECREMENT_ACTION";
export const BASKET_CHECKOUT = "SET_BASKET_CHECKOUT_ACTION";
